[project]
name = "mcp-kinetica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.7.1",
    "gpudb>=7.2.2.9",
]
